// <auto-generated />
using System;
using CrochetHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrochetHub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260514083024_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CrochetHub.Models.AuditLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LogID"));

                    b.Property<int?>("ActionID")
                        .HasColumnType("int");

                    b.Property<int?>("EntityID")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NewValue")
                        .HasColumnType("longtext");

                    b.Property<string>("OldValue")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("LogID");

                    b.HasIndex("ActionID");

                    b.HasIndex("UserID");

                    b.ToTable("auditlog", (string)null);
                });

            modelBuilder.Entity("CrochetHub.Models.Course", b =>
                {
                    b.Property<int>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CourseID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("DifficultyID")
                        .HasColumnType("int");

                    b.Property<int>("InstructorID")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailURL")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("CourseID");

                    b.HasIndex("DifficultyID");

                    b.HasIndex("InstructorID");

                    b.ToTable("course", (string)null);
                });

            modelBuilder.Entity("CrochetHub.Models.CourseEnrollment", b =>
                {
                    b.Property<int>("EnrollmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EnrollmentID"));

                    b.Property<decimal>("CompletionPercentage")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentID");

                    b.HasIndex("CourseID");

                    b.HasIndex("StudentID", "CourseID")
                        .IsUnique();

                    b.ToTable("courseenrollment", (string)null);
                });

            modelBuilder.Entity("CrochetHub.Models.CoursePrerequisite", b =>
                {
                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<int>("PrerequisiteID")
                        .HasColumnType("int");

                    b.HasKey("CourseID", "PrerequisiteID");

                    b.HasIndex("PrerequisiteID");

                    b.ToTable("courseprerequisites", (string)null);
                });

            modelBuilder.Entity("CrochetHub.Models.CourseReview", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("ReviewID");

                    b.HasIndex("CourseID");

                    b.HasIndex("StudentID", "CourseID")
                        .IsUnique();

                    b.ToTable("coursereview", (string)null);
                });

            modelBuilder.Entity("CrochetHub.Models.CourseTag", b =>
                {
                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<int>("TagID")
                        .HasColumnType("int");

                    b.HasKey("CourseID", "TagID");

                    b.HasIndex("TagID");

                    b.ToTable("coursetag", (string)null);
                });

            modelBuilder.Entity("CrochetHub.Models.ForumReply", b =>
                {
                    b.Property<int>("ReplyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReplyID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ThreadID")
                        .HasColumnType("int");

                    b.Property<int>("Upvotes")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ReplyID");

                    b.HasIndex("ThreadID");

                    b.HasIndex("UserID");

                    b.ToTable("forumreply", (string)null);
                });

            modelBuilder.Entity("CrochetHub.Models.ForumThread", b =>
                {
                    b.Property<int>("ThreadID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ThreadID"));

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ThreadID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("UserID");

                    b.ToTable("forumthread", (string)null);
                });

            modelBuilder.Entity("CrochetHub.Models.Instructor", b =>
                {
                    b.Property<int>("InstructorID")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("longtext");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("int");

                    b.HasKey("InstructorID");

                    b.ToTable("instructor", (string)null);
                });

            modelBuilder.Entity("CrochetHub.Models.Lesson", b =>
                {
                    b.Property<int>("LessonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LessonID"));

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("VideoURL")
                        .HasColumnType("longtext");

                    b.HasKey("LessonID");

                    b.HasIndex("CourseID");

                    b.ToTable("lesson", (string)null);
                });

            modelBuilder.Entity("CrochetHub.Models.Lookup", b =>
                {
                    b.Property<int>("LookupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LookupID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("LookupID");

                    b.ToTable("lookup", (string)null);

                    b.HasData(
                        new
                        {
                            LookupID = 1,
                            Category = "GENDER",
                            Value = "Male"
                        },
                        new
                        {
                            LookupID = 2,
                            Category = "GENDER",
                            Value = "Female"
                        },
                        new
                        {
                            LookupID = 3,
                            Category = "DIFFICULTY",
                            Value = "Beginner"
                        },
                        new
                        {
                            LookupID = 4,
                            Category = "DIFFICULTY",
                            Value = "Intermediate"
                        },
                        new
                        {
                            LookupID = 5,
                            Category = "DIFFICULTY",
                            Value = "Advanced"
                        },
                        new
                        {
                            LookupID = 6,
                            Category = "ROLE",
                            Value = "Student"
                        },
                        new
                        {
                            LookupID = 7,
                            Category = "ROLE",
                            Value = "Instructor"
                        },
                        new
                        {
                            LookupID = 8,
                            Category = "ROLE",
                            Value = "Admin"
                        },
                        new
                        {
                            LookupID = 9,
                            Category = "FORUM_CATEGORY",
                            Value = "Beginner Help"
                        },
                        new
                        {
                            LookupID = 10,
                            Category = "FORUM_CATEGORY",
                            Value = "Pattern Sharing"
                        },
                        new
                        {
                            LookupID = 11,
                            Category = "FORUM_CATEGORY",
                            Value = "Tools and Materials"
                        },
                        new
                        {
                            LookupID = 12,
                            Category = "FORUM_CATEGORY",
                            Value = "General Discussion"
                        },
                        new
                        {
                            LookupID = 13,
                            Category = "NOTIFICATION_TYPE",
                            Value = "Enrollment"
                        },
                        new
                        {
                            LookupID = 14,
                            Category = "NOTIFICATION_TYPE",
                            Value = "Reply"
                        },
                        new
                        {
                            LookupID = 15,
                            Category = "NOTIFICATION_TYPE",
                            Value = "Achievement"
                        },
                        new
                        {
                            LookupID = 16,
                            Category = "NOTIFICATION_TYPE",
                            Value = "System"
                        },
                        new
                        {
                            LookupID = 17,
                            Category = "ACTION",
                            Value = "INSERT"
                        },
                        new
                        {
                            LookupID = 18,
                            Category = "ACTION",
                            Value = "UPDATE"
                        },
                        new
                        {
                            LookupID = 19,
                            Category = "ACTION",
                            Value = "DELETE"
                        });
                });

            modelBuilder.Entity("CrochetHub.Models.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NotificationID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("TypeID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("NotificationID");

                    b.HasIndex("TypeID");

                    b.HasIndex("UserID");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("CrochetHub.Models.Pattern", b =>
                {
                    b.Property<int>("PatternID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PatternID"));

                    b.Property<int?>("CourseID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("DifficultyID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("PatternID");

                    b.HasIndex("CourseID");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DifficultyID");

                    b.ToTable("pattern", (string)null);
                });

            modelBuilder.Entity("CrochetHub.Models.PatternMaterial", b =>
                {
                    b.Property<int>("MaterialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaterialID"));

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("PatternID")
                        .HasColumnType("int");

                    b.Property<string>("Quantity")
                        .HasColumnType("longtext");

                    b.HasKey("MaterialID");

                    b.HasIndex("PatternID");

                    b.ToTable("patternmaterial", (string)null);
                });

            modelBuilder.Entity("CrochetHub.Models.PatternReview", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PatternID")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ReviewID");

                    b.HasIndex("PatternID");

                    b.HasIndex("UserID", "PatternID")
                        .IsUnique();

                    b.ToTable("patternreview", (string)null);
                });

            modelBuilder.Entity("CrochetHub.Models.PatternTag", b =>
                {
                    b.Property<int>("PatternID")
                        .HasColumnType("int");

                    b.Property<int>("TagID")
                        .HasColumnType("int");

                    b.HasKey("PatternID", "TagID");

                    b.HasIndex("TagID");

                    b.ToTable("patterntag", (string)null);
                });

            modelBuilder.Entity("CrochetHub.Models.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PersonID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("GenderID")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("PersonID");

                    b.HasIndex("GenderID");

                    b.ToTable("person", (string)null);

                    b.HasData(
                        new
                        {
                            PersonID = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Admin",
                            GenderID = 1,
                            LastName = "User"
                        });
                });

            modelBuilder.Entity("CrochetHub.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EnrollmentDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("StudentID");

                    b.ToTable("student", (string)null);
                });

            modelBuilder.Entity("CrochetHub.Models.StudentProgress", b =>
                {
                    b.Property<int>("ProgressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProgressID"));

                    b.Property<bool>("Completed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LessonID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<int>("TimeSpent")
                        .HasColumnType("int");

                    b.HasKey("ProgressID");

                    b.HasIndex("LessonID");

                    b.HasIndex("StudentID", "LessonID")
                        .IsUnique();

                    b.ToTable("studentprogress", (string)null);
                });

            modelBuilder.Entity("CrochetHub.Models.Tag", b =>
                {
                    b.Property<int>("TagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TagID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("TagID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tag", (string)null);
                });

            modelBuilder.Entity("CrochetHub.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleID");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@crochethub.com",
                            PasswordHash = "$2a$11$0ftU8Iyoqqem5Ezf7zGKe.qPNNjJipaENcVTopn5zjNoC9exiT.6q",
                            RoleID = 8
                        });
                });

            modelBuilder.Entity("CrochetHub.Models.Views.CoursePrerequisitesView", b =>
                {
                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<string>("CourseTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Difficulty")
                        .HasColumnType("longtext");

                    b.Property<string>("PrerequisiteChain")
                        .HasColumnType("longtext");

                    b.ToTable((string)null);

                    b.ToView("v_course_prerequisites", (string)null);
                });

            modelBuilder.Entity("CrochetHub.Models.Views.ForumActivityView", b =>
                {
                    b.Property<decimal>("AvgUpvotesPerReply")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RepliesPosted")
                        .HasColumnType("int");

                    b.Property<int>("ThreadsCreated")
                        .HasColumnType("int");

                    b.Property<int>("TotalUpvotes")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("v_forum_activity", (string)null);
                });

            modelBuilder.Entity("CrochetHub.Models.Views.InstructorStatsView", b =>
                {
                    b.Property<decimal>("AvgCompletion")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("AvgRating")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("InstructorID")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TotalEnrolled")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("v_instructor_stats", (string)null);
                });

            modelBuilder.Entity("CrochetHub.Models.Views.PatternDifficultyStatsView", b =>
                {
                    b.Property<decimal>("AvgRating")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("CreatorCount")
                        .HasColumnType("int");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PatternCount")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("v_pattern_difficulty_stats", (string)null);
                });

            modelBuilder.Entity("CrochetHub.Models.Views.StudentNextCoursesView", b =>
                {
                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<string>("Difficulty")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NextCourse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PrerequisitesRequired")
                        .HasColumnType("int");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("v_student_next_courses", (string)null);
                });

            modelBuilder.Entity("CrochetHub.Models.Views.StudentProgressView", b =>
                {
                    b.Property<int>("CompletedLessons")
                        .HasColumnType("int");

                    b.Property<decimal>("CompletionPercentage")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<int>("TotalLessons")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("v_student_progress", (string)null);
                });

            modelBuilder.Entity("CrochetHub.Models.AuditLog", b =>
                {
                    b.HasOne("CrochetHub.Models.Lookup", "Action")
                        .WithMany()
                        .HasForeignKey("ActionID");

                    b.HasOne("CrochetHub.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CrochetHub.Models.Course", b =>
                {
                    b.HasOne("CrochetHub.Models.Lookup", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyID");

                    b.HasOne("CrochetHub.Models.Instructor", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("CrochetHub.Models.CourseEnrollment", b =>
                {
                    b.HasOne("CrochetHub.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrochetHub.Models.Student", "Student")
                        .WithMany("CourseEnrollments")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CrochetHub.Models.CoursePrerequisite", b =>
                {
                    b.HasOne("CrochetHub.Models.Course", "Course")
                        .WithMany("Prerequisites")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrochetHub.Models.Course", "Prerequisite")
                        .WithMany()
                        .HasForeignKey("PrerequisiteID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Prerequisite");
                });

            modelBuilder.Entity("CrochetHub.Models.CourseReview", b =>
                {
                    b.HasOne("CrochetHub.Models.Course", "Course")
                        .WithMany("Reviews")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrochetHub.Models.Student", "Student")
                        .WithMany("CourseReviews")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CrochetHub.Models.CourseTag", b =>
                {
                    b.HasOne("CrochetHub.Models.Course", "Course")
                        .WithMany("CourseTags")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrochetHub.Models.Tag", "Tag")
                        .WithMany("CourseTags")
                        .HasForeignKey("TagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("CrochetHub.Models.ForumReply", b =>
                {
                    b.HasOne("CrochetHub.Models.ForumThread", "Thread")
                        .WithMany("Replies")
                        .HasForeignKey("ThreadID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrochetHub.Models.User", "User")
                        .WithMany("ForumReplies")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thread");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CrochetHub.Models.ForumThread", b =>
                {
                    b.HasOne("CrochetHub.Models.Lookup", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID");

                    b.HasOne("CrochetHub.Models.User", "User")
                        .WithMany("ForumThreads")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CrochetHub.Models.Instructor", b =>
                {
                    b.HasOne("CrochetHub.Models.User", "User")
                        .WithOne("Instructor")
                        .HasForeignKey("CrochetHub.Models.Instructor", "InstructorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CrochetHub.Models.Lesson", b =>
                {
                    b.HasOne("CrochetHub.Models.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CrochetHub.Models.Notification", b =>
                {
                    b.HasOne("CrochetHub.Models.Lookup", "Type")
                        .WithMany()
                        .HasForeignKey("TypeID");

                    b.HasOne("CrochetHub.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CrochetHub.Models.Pattern", b =>
                {
                    b.HasOne("CrochetHub.Models.Course", "Course")
                        .WithMany("Patterns")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CrochetHub.Models.User", "Creator")
                        .WithMany("Patterns")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CrochetHub.Models.Lookup", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyID");

                    b.Navigation("Course");

                    b.Navigation("Creator");

                    b.Navigation("Difficulty");
                });

            modelBuilder.Entity("CrochetHub.Models.PatternMaterial", b =>
                {
                    b.HasOne("CrochetHub.Models.Pattern", "Pattern")
                        .WithMany("Materials")
                        .HasForeignKey("PatternID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pattern");
                });

            modelBuilder.Entity("CrochetHub.Models.PatternReview", b =>
                {
                    b.HasOne("CrochetHub.Models.Pattern", "Pattern")
                        .WithMany("Reviews")
                        .HasForeignKey("PatternID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrochetHub.Models.User", "User")
                        .WithMany("PatternReviews")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pattern");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CrochetHub.Models.PatternTag", b =>
                {
                    b.HasOne("CrochetHub.Models.Pattern", "Pattern")
                        .WithMany("PatternTags")
                        .HasForeignKey("PatternID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrochetHub.Models.Tag", "Tag")
                        .WithMany("PatternTags")
                        .HasForeignKey("TagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pattern");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("CrochetHub.Models.Person", b =>
                {
                    b.HasOne("CrochetHub.Models.Lookup", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderID");

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("CrochetHub.Models.Student", b =>
                {
                    b.HasOne("CrochetHub.Models.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("CrochetHub.Models.Student", "StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CrochetHub.Models.StudentProgress", b =>
                {
                    b.HasOne("CrochetHub.Models.Lesson", "Lesson")
                        .WithMany("StudentProgresses")
                        .HasForeignKey("LessonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrochetHub.Models.Student", "Student")
                        .WithMany("StudentProgresses")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CrochetHub.Models.User", b =>
                {
                    b.HasOne("CrochetHub.Models.Lookup", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrochetHub.Models.Person", "Person")
                        .WithOne("User")
                        .HasForeignKey("CrochetHub.Models.User", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CrochetHub.Models.Course", b =>
                {
                    b.Navigation("CourseTags");

                    b.Navigation("Enrollments");

                    b.Navigation("Lessons");

                    b.Navigation("Patterns");

                    b.Navigation("Prerequisites");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("CrochetHub.Models.ForumThread", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("CrochetHub.Models.Instructor", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("CrochetHub.Models.Lesson", b =>
                {
                    b.Navigation("StudentProgresses");
                });

            modelBuilder.Entity("CrochetHub.Models.Pattern", b =>
                {
                    b.Navigation("Materials");

                    b.Navigation("PatternTags");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("CrochetHub.Models.Person", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("CrochetHub.Models.Student", b =>
                {
                    b.Navigation("CourseEnrollments");

                    b.Navigation("CourseReviews");

                    b.Navigation("StudentProgresses");
                });

            modelBuilder.Entity("CrochetHub.Models.Tag", b =>
                {
                    b.Navigation("CourseTags");

                    b.Navigation("PatternTags");
                });

            modelBuilder.Entity("CrochetHub.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("ForumReplies");

                    b.Navigation("ForumThreads");

                    b.Navigation("Instructor");

                    b.Navigation("Notifications");

                    b.Navigation("PatternReviews");

                    b.Navigation("Patterns");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
